name: toondo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  data:
    path: packages/data
  domain:
    path: packages/domain
  presentation:
    path: packages/presentation
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  uuid: ^4.5.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.1.2
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  mockito: ^5.4.4
  postgres: ^3.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  patrol: ^3.13.2
  rive: ^0.13.20
  get_it: ^8.0.3
  audioplayers: ^6.1.1
  injectable: ^2.5.0
  flutter_gen:
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  hive_test: ^1.0.1
  change_app_package_name: ^1.4.0 
  injectable_generator: ^2.6.2
  flutter_gen_runner:
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/rives/
    - assets/audios/

flutter_gen:
  output: packages/common/lib/gen # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  fonts:
    enabled: true             # FontFamily.dart 생성 여부 (default: true)

  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true