name: todo_with_alarm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  uuid: ^4.5.0
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  table_calendar: ^3.1.2
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
